### ISSUE TITLE
feat: return type predicate

### ISSUE THREAD

**Issue by privatenumber** [sindresorhus/has-own-prop#3]
I read [this blogpost](https://fettblog.eu/typescript-hasownproperty/) by @ddprrt that offered a solution to making a custom `hasOwnProperty` that returns a type predicate:

```ts
function hasOwnProperty<X extends {}, Y extends PropertyKey>
  (obj: X, prop: Y): obj is X & Record<Y, unknown> {
  return obj.hasOwnProperty(prop)
}
```

The type will diverge from TypeScript's native `hasOwnProperty` type, but what do you think of this enhancement?

**Comment by sindresorhus** [comment]
👍 PR welcome.

**Comment by ddprrt** [comment]
Cool! 👏
